fedbiomed/fedbiomed

README.md
test PR from a developer, not member of organization but member of repository
=> misc dummy test

README.md
The following Pull Request adds to the already existing badges:
- PRs welcome, redirecting to Pull Requests webpage
- cite , redirecting to white paper
- python with all python version supported in Fed-BioMed
- License, redirecting to the License.md
=> adding extra badges to README

envs/development/conda/fedbiomed-network.yaml, envs/development/docker/restful/build_files/requirements.txt, envs/development/docker/restful/run_mounts/app/fedbiomed/urls.py, envs/vpn/docker/restful/build_files/requirements.txt, envs/vpn/docker/restful/run_mounts/app/fedbiomed/urls.py
Upgrade Django version (very partial address of #448, ahead of other items, because django contains some security issue)
Tested with running basic example in `dev` mode + building and launching `vpn` restful container (did not run a full test).
**License**
```
``` …
=> fix django old version

CHANGELOG.md, fedbiomed/common/constants.py, fedbiomed/common/secagg/_jls.py
Closes #789 
This merge request fixes the issues regarding vector encoding. 
Before merging please make sure that the pipelines are successful. After the checkes are succeed please push a patch tag and merge it to master. 
Please restore the branch and merge to develop after merging into master completed. 
**License**
Project code files should …
=> fixes vector encoding elementsize

docs/assets/css/style.css
Fixes icon size in table view.
**License**
```
``` …
=> Fixes icon size in table view

README.md
Misc fix for README.md badge for python version 3.9 => 3.10 as mentionned in:
https://github.com/fedbiomed/fedbiomed/pull/822#issuecomment-1652008406
**License**
```
```
They …
=> python badge update 3.10

docs/.templates/theme/docs.html, docs/.templates/theme/include/header.html, docs/.templates/theme/include/sidebar-doc.html, docs/.templates/theme/main.html, mkdocs.yml, scripts/docs/redirect.html
This PR contains following changes:
- Uses HTML5 semantic tags to create more SEO friendly HTML content 
- Fixes warnings raised by Google Search Console due to redirection index issue. Fix has been done by adding canonical URL and permanent redirection. 
- Corrects URLs in sitemap.xml -> URLs pages addresses fedbiomed.org/latest  
**License** …
=> SEO friendly improvements for documentation site

scripts/configure_conda
Solve #883 
**License**
```
``` …
=> Show conda error messages #883

docs/.templates/theme/docs.html
TO_BE_FILLED_BY_PR_CREATOR
**License**
```
``` …
=> fixes download link for notebooks

CHANGELOG.md, RELEASE.md, fedbiomed/common/constants.py
Release v4.5.0 to develop
**License**
```
``` …
=> release v4.5.0 to develop

CONTRIBUTING.md, README.md, docs/.templates/theme/home.html, docs/developer/testing-in-fedbiomed.md, docs/developer/usage_and_tools.md, docs/getting-started/fedbiomed-architecture.md, docs/getting-started/fedbiomed-workflow.md, docs/getting-started/getting-started.md, docs/getting-started/what-is-fedbiomed.md, docs/index.md, docs/pages/about-us.md, mkdocs.yml
Misc documentation : as discussed with Marco change motto in doc front pages from "Federated Learning" to "Collaborative Learning" (long: "Collaborative Learning, including Federated Learning and Federated Analytics"
**License**
```
```
Code files can be reused …
=> misc doc motto to "collaborative learning"

docs/user-guide/deployment/deployment-vpn-node2.md, docs/user-guide/deployment/deployment-vpn.md, docs/user-guide/secagg/configuration.md, fedbiomed/common/certificate_manager.py, scripts/fedbiomed_run
Fix #929 
- quick and dirty to `fedbiomed_run` regression introduced by new syntax `fedbiomed_run configuration create`
- extend certificate with subject alternative name (SAN) extension for IP address, when the server is a IP instead of a name (incorrect cert format)
**License**
Project code files should begin with these comment lines to help …
=> Regression bugs from gRPC TLS 

docs/tutorials/medical/medical-image-segmentation-unet-library.ipynb, notebooks/medical-image-segmentation/medical-image-segmentation-custom-unet-code.ipynb, notebooks/medical-image-segmentation/medical-image-segmentation-unet-library.ipynb
Misc fix in notebook, no issue, found during last check before release.
**License**
```
```
The `CREDIT.md` …
=> misc fix in medical folder dataset notebook

CHANGELOG.md, fedbiomed/common/constants.py
release v5.1.0 backmerge to develop
**License**
```
``` …
=> prepare release v5.1.0

fedbiomed/common/cli.py, tests/test_common_cli.py
Fix #1014 
**License**
```
``` …
=> minimal fix for regression

fedbiomed/node/cli_utils/_training_plan_management.py, fedbiomed/researcher/federated_workflows/_training_plan_workflow.py, fedbiomed/researcher/federated_workflows/jobs/__init__.py, fedbiomed/researcher/federated_workflows/jobs/_job.py, fedbiomed/researcher/federated_workflows/jobs/_training_job.py, fedbiomed/researcher/federated_workflows/jobs/_training_plan_approval_job.py, tests/test_experiment.py, tests/test_job.py, tests/test_training_plan_workflow.py
Finishes addressing #1031
**License**
```
``` …
=> continue rewrite `Job()` interface API 

fedbiomed/researcher/federated_workflows/_experiment.py, fedbiomed/researcher/federated_workflows/jobs/_job.py
Removes unused class members, please see #1022 
Closes #1022 
**License**
```
```
The `CREDIT.md` file and …
=> Removes unused class members

fedbiomed/researcher/federated_workflows/_experiment.py, fedbiomed/researcher/federated_workflows/_federated_workflow.py, fedbiomed/researcher/federated_workflows/_training_plan_workflow.py, tests/test_federated_workflow.py, tests/test_training_plan_workflow.py
Address #1029
- Shorten long lines
- Update var names used for typing according the `typing` recommendations.
- Raise correct exceptions FederatedTrainingPlan
- Corrects passing empty list to `set_tags` 
- Updates training_data at any call of `set_tags`
**License** …
=> Review federated workflow

fedbiomed/researcher/federated_workflows/_experiment.py, fedbiomed/researcher/federated_workflows/_federated_workflow.py, fedbiomed/researcher/federated_workflows/_training_plan_workflow.py, fedbiomed/researcher/node_state_agent.py, tests/test_experiment.py, tests/test_federated_workflow.py, tests/test_training_plan_workflow.py
Related to #1030 
This PR proposes changes in the API, and a few optimizations regarding existing code.
It also re-introduces a object setup checking facility, that checks whether object exists or not, before running an Experiment
**License**
```
```
Code files can …
=> Experiment review and redesign

docs/tutorials/security/training-with-approved-training-plans.ipynb
Mini fix for `./scripts/docs/fedbiomed_doc.sh serve`
**License**
```
``` …
=> mini fix to build doc

README.md, docs/tutorials/optimizers/01-fedopt-and-scaffold.ipynb, docs/user-guide/advanced-optimization.md, docs/user-guide/nodes/configuring-nodes.md, docs/user-guide/nodes/deploying-datasets.md, docs/user-guide/nodes/node-gui.md, docs/user-guide/nodes/training-plan-security-manager.md, docs/user-guide/researcher/aggregation.md, docs/user-guide/researcher/experiment.md, docs/user-guide/researcher/index.md, docs/user-guide/researcher/model-testing-during-federated-training.md, docs/user-guide/secagg/configuration.md, envs/vpn/docker/gui/build_files/Dockerfile, envs/vpn/docker/gui/build_files/entrypoint.bash, fedbiomed/researcher/federated_workflows/_experiment.py, fedbiomed/researcher/federated_workflows/_federated_workflow.py, mkdocs.yml, scripts/fedbiomed_run
Partial #1042 
- review documentation of `User Guide` (for changes in #896, plus update obsolete entries and fix typos)
- misc docstrings, etc. changes detected in other locations
Following our discussion on discord, related issue #1070 was created. 
**License** …
=> Documentation review of `User Guide`

docs/tutorials/advanced/in-depth-experiment-configuration.ipynb, docs/tutorials/optimizers/01-fedopt-and-scaffold.ipynb, docs/tutorials/pytorch/05-Aggregation_in_Fed-BioMed.ipynb, docs/tutorials/security/secure-aggregation.ipynb, docs/user-guide/nodes/node-gui.md, docs/user-guide/researcher/aggregation.md, docs/user-guide/researcher/experiment.md, notebooks/general-tutorial-exp-interface.ipynb, notebooks/general-tutorial-secagg.ipynb
Removes mention to previous API, where methods `set_aggregator` and `set_strategy` where accepting instances and type of objects. Now it only accepts instances.
Closes #1058 .
**License**
```
```
Code files can be reused from another project with a compatible …
=> Updating documentation removing references to former api

envs/build/conda/fedbiomed-doc.yaml, envs/build/docs-requirements.txt
This PR upgrades mkdocstring version to solve rendering issue for class methods
**License**
```
```
The …
=> Upgrade mkdocstrings

fedbiomed/researcher/federated_workflows/_experiment.py, fedbiomed/researcher/federated_workflows/_training_plan_workflow.py, tests/test_training_plan_workflow.py
=> completes training plan workflow unittests

fedbiomed/researcher/federated_workflows/_federated_workflow.py, tests/test_federated_workflow.py
=> completes federated workflow unittests

tests/end2end/e2e_ixi_brain_segmentation.py, tests/end2end/experiments/training_plans/ixi_brain_segmentation.py
Edit @srcansiz : Please do not merge before #1098 
Add another end2ned test based on `MedicalFolderDataset` and brain segmentation task.
=> Add brain segmentation test

docs/tutorials/concrete-ml/concrete-ml.ipynb
Quick PR to integrate a couple of typos and improvementes spotted by Riccardo.
**License**
```
```
The …
=> fixed typos

CHANGELOG.md, RELEASE.md, fedbiomed/common/constants.py
This commit mainly contains change regarding the new version of Fed-BioMed, ie:
- renaming v5.1.0 to v5.2.0
- listing all changes in the `CHANGELOG.md` file
as specified in the process (please see `RELEASE.md` for further information)
**License**
```
```
Code files …
=> Updates Fed-BioMed files for realease v5.2.0

tests/end2end/experiments/training_plans/mnist_pytorch_training_plan.py
TO_BE_FILLED_BY_PR_CREATOR
**License**
```
``` …
=> change network size for endurance tests

fedbiomed/common/constants.py, fedbiomed/common/message.py, fedbiomed/common/secagg/__init__.py, fedbiomed/common/secagg/_secagg_dummy_crypter.py, fedbiomed/common/secagg_manager.py, fedbiomed/node/node.py, fedbiomed/node/round.py, fedbiomed/node/secagg_dummy_setup.py, fedbiomed/node/secagg_manager.py, fedbiomed/researcher/federated_workflows/_federated_workflow.py, fedbiomed/researcher/federated_workflows/jobs/_training_job.py, fedbiomed/researcher/secagg/_secure_aggregation.py
**TO BE MERGED AFTER #1129 #1133**
**License**
```
``` …
=> Extend skeleton for LOM secure aggregation training

fedbiomed/node/node.py, fedbiomed/node/round.py, fedbiomed/node/secure_aggregation.py
Addresses #1143 
- refactor
- remove obsolete/redundant checks
**License**
```
```
The `CREDIT.md` file and …
=> Refactor node side secagg checks in `Round`

fedbiomed/common/message.py, fedbiomed/common/secagg/_lom.py, fedbiomed/common/secagg/_secagg_crypter.py, fedbiomed/common/secagg_manager.py, fedbiomed/node/round.py, fedbiomed/node/secagg.py, fedbiomed/node/secure_aggregation.py, fedbiomed/researcher/federated_workflows/_federated_workflow.py, fedbiomed/researcher/secagg/_secagg_context.py, tests/test_dh.py, tests/test_experiment.py, tests/test_federated_workflow.py, tests/test_job.py, tests/test_lom.py, tests/test_message.py, tests/test_node.py, tests/test_round.py, tests/test_secagg_crypter.py, tests/test_secagg_manager_common.py, tests/test_secagg_manager_node.py, tests/test_secagg_node.py, tests/test_secagg_researcher.py, tests/test_transport_node_agent.py, tests/test_transport_server.py, tests/testsupport/fake_researcher_secagg.py
Fixes unit tests for secure aggregation
Closes #1141 
**License**
```
``` …
=> Unit tests fixes for Secure Aggregation

CODING_RULES.md, docs/developer/usage_and_tools.md
Completes #1144
**License**
```
``` …
=> update coding rules for commit/push/pull/merge vs rebase guidelines

envs/build/conda/fedbiomed-doc.yaml, envs/build/docs-requirements.txt
=> upgrade mkdocstrings-python module

.github/workflows/end-to-end.yml, docs/tutorials/advanced/in-depth-experiment-configuration.ipynb, docs/user-guide/researcher/model-testing-during-federated-training.md, docs/user-guide/researcher/tensorboard.md, fedbiomed/common/data/_data_manager.py, fedbiomed/common/data/_sklearn_data_manager.py, fedbiomed/common/data/_torch_data_manager.py, fedbiomed/common/metrics.py, fedbiomed/common/training_args.py, fedbiomed/common/training_plans/_base_training_plan.py, fedbiomed/common/training_plans/_training_iterations.py, fedbiomed/node/round.py, fedbiomed/researcher/monitor.py, notebooks/flamby-integration-into-fedbiomed.ipynb, tests/end2end/e2e_mnist_pytorch.py, tests/test_base_training_plan.py, tests/test_fedbiosklearn.py, tests/test_sklearn_data_manager.py, tests/test_torch_data_manager.py, tests/test_torchnn.py
This PR adds the testing_batch_size feature to the testing facility, in order to fix the issue depicted https://github.com/fedbiomed/fedbiomed/issues/893 , ie partially fixing issues where testing dataset triggers a Node `MemoryError`, by computing testing metrics in batches instead of the whole dataset.
This feature is disabled by setting `test_batch_size=None` or `test_batch_size=0` entry, to be set in the `TrainingArgs`.
Closes #893.
**Warning**
There is an issue (not due to this new feature) that has been spotted while developing: if `test_batch_size=1`. then an error is triggered complaining that prediction and targets don't have the same size (see issue https://github.com/fedbiomed/fedbiomed/issues/1013 ). This issue is still not solved with this new feature. …
=> New feature: testing batch size

docs/user-guide/deployment/deployment-vpn-node2.md, docs/user-guide/deployment/deployment-vpn-secagg.md, docs/user-guide/deployment/deployment-vpn.md, docs/user-guide/nodes/configuring-nodes.md, envs/vpn/docker/researcher/build_files/Dockerfile, envs/vpn/docker/researcher/build_files/entrypoint.bash, fedbiomed/common/config.py, fedbiomed/common/environ.py, fedbiomed/node/config.py, fedbiomed/node/environ.py, fedbiomed/node/round.py, fedbiomed/node/secagg/_secagg_round.py, fedbiomed/researcher/config.py, fedbiomed/researcher/environ.py, fedbiomed/researcher/federated_workflows/_federated_workflow.py, fedbiomed/researcher/secagg/_secagg_context.py, fedbiomed/researcher/secagg/_secure_aggregation.py, fedbiomed/researcher/strategies/default_strategy.py, tests/end2end/e2e_secure_aggregation.py, tests/test_node_environ.py, tests/test_researcher_environ.py, tests/test_secure_aggregation.py, tests/testsupport/fake_node_environ.py, tests/testsupport/fake_researcher_environ.py
- implement #804 for making secagg insecure validation optional
- misc: fix for secagg end2end test & `DefaultStrategy()` ; adapt VPN documentation for LOM secagg ; update `Environ` docstrings
**License**
```
```
Code files can be reused from another project with a …
=> Make secagg insecure validation optional

tests/test_transport_server.py
=> Add some missing tests in transport server

tests/test_federated_workflow.py
Partial #942 unit tests:
- update unit tests for FederatedWorkflow with LOM secagg
**License**
```
```
The …
=> Update unit tests for FederatedWorkflow with LOM secagg

docs/tutorials/security/secure-aggregation.ipynb
Misc fix for secagg tutorial notebook. No associated issue.
**License**
```
```
The `CREDIT.md` file and …
=> Misc fix for secagg tutorial notebook

CHANGELOG.md, RELEASE.md, fedbiomed/common/constants.py
Release v5.3.0 backmerge to `develop`
**License**
```
``` …
=> Release v5.3.0 backmerge to `develop`

fedbiomed/node/requests/_n2n_router.py, fedbiomed/node/requests/_overlay.py, fedbiomed/node/requests/_send_nodes.py, tests/test_common_channel_manager.py, tests/test_node_n2n_controller.py, tests/test_node_n2n_router.py, tests/test_node_overlay.py, tests/test_node_send_nodes.py, tests/test_secagg_manager_common.py, tests/testsupport/fake_tiny_db.py
**WARNING: please merge after #1218 as it includes this branch**
Partial #1195 : add unit tests for new code
**License**
```
```
They shall retain the original license and …
=> Add unit tests for node to node secure communications

fedbiomed/common/secagg/_lom.py, fedbiomed/common/secagg/_secagg_crypter.py, fedbiomed/common/utils/_secagg_utils.py, fedbiomed/researcher/secagg/_secure_aggregation.py, tests/end2end/e2e_secure_aggregation.py, tests/test_lom.py, tests/test_secure_aggregation.py
**IMPORTANT: merge after #1228 as it is included into this branch**
Address #1198
- clarify the `nonce` generation for LOM secagg, which is then used for `ChaCha20` symmetric encryption
**License**
```
```
Code files can be reused from another project with a …
=> Clarify nonce generation for LOM secagg

docs/user-guide/deployment/deployment-vpn.md, envs/development/conda/fedbiomed-researcher-macosx.yaml, envs/development/conda/fedbiomed-researcher.yaml, envs/vpn/conda/fedbiomed-researcher.yaml, envs/vpn/docker/docker-compose.yml, envs/vpn/docker/docker-compose_run_node.yml, envs/vpn/docker/researcher/build_files/Dockerfile
~~**CAVEAT: merge after #1228 #1230 as they are included in this branch**~~
Info: now rebased on new version of `develop`
Address #1194
**License**
```
```
They shall retain …
=> Fix researcher jupyter notebook token automatic

AUTHORS.md, docs/developer/usage_and_tools.md
Address #1255
**License**
```
``` …
=> misc update dev doc for "new feature" label

docs/developer/usage_and_tools.md
=> Adds improvement label

fedbiomed/common/ipython.py
This PR improves integration of Fed-BioMed with Google Colab by allowing our `is_ipython` function to correctly identify Colab's notebook environment.
This patch was tested in the context of a practical demo session. 
**License**
```
```
Code files can be reused …
=> Improve Colab integration

CHANGELOG.md, fedbiomed/__init__.py
Pre-release changes
**License**
```
```
The `CREDIT.md` file and `credit/` directory shall be completed and …
=> Release candidate

mkdocs.yml
Missing link in news feed
**License**
```
``` …
=> Missing link to news feed

docs/getting-started/installation.md, docs/support/troubleshooting.md, docs/user-guide/installation/windows-installation.md
Updates windows installation steps
**License**
```
``` …
=> Updates documentation for Fed-BioMed installation on windows 11

docs/.templates/theme/home.html, docs/.templates/theme/main.html, docs/tutorials/pytorch/01_PyTorch_MNIST_Single_Node_Tutorial.ipynb
Add button on home page for asking for stars on github
Reviewer: the added text ("please add ...") and the button are on 2 different lines. When putting on same line, I could not have proper alignement. This may be an improvement to the PR. 
**License**
```
``` …
=> add button for stars on github

fedbiomed/common/dataset/_medical_datasets.py, fedbiomed/common/dataset/flamby_dataset.py, fedbiomed/common/message.py, fedbiomed/common/models/_sklearn.py, fedbiomed/common/training_plans/_base_training_plan.py, fedbiomed/common/training_plans/_sklearn_models.py, fedbiomed/common/training_plans/_sklearn_training_plan.py, fedbiomed/common/utils/__init__.py, fedbiomed/common/validator.py, fedbiomed/node/cli.py, fedbiomed/node/round.py, fedbiomed/researcher/monitor.py, fedbiomed/researcher/secagg/_secure_aggregation.py, fedbiomed/transport/protocols/researcher_pb2.py
Some proposed solutions for issues raised by linter ruff.
**License**
```
```
The `CREDIT.md` file and …
=> Partial corrections, first part

docs/developer/usage_and_tools.md
No issue, discussed in dev team
**License**
```
``` …
=> Misc dev doc update

fedbiomed/common/dataset_controller/_medical_folder_controller.py, fedbiomed/common/dataset_reader/_csv_reader.py, pdm.lock, pyproject.toml, tests/test_csv_reader.py
Stupidly read a csv file with `CsvReader` and then converts it to a pandas dataframe
**License**
```
```
The …
=> implmenting csv reader in medical folder dataset

fedbiomed/common/dataset_controller/_medical_folder_controller.py, fedbiomed/common/dataset_reader/_nifti_reader.py, tests/test_dataset_controllers/test_mfd_controller.py, tests/test_medical_datasets.py
=> Uses NiftiReader in MFC (MedicalFolderController) and writes unit tests for MFC

docs/user-guide/datasets/custom-dataset.md, fedbiomed/common/dataset/_custom_dataset.py, tests/test_dataset/test_custom_dataset.py
- Implements CustomDataset class that allows user to define their custom datasets respecting the federated workflow defined in Fed-BioMed
- Implements unittests for CustomDataset
- `complete_initialization` takes `path` as argument rather than `controller_args`, this is to discuss. 
- Writes docs to explain how CustomDataset can be used in training plan. 
- you did not steal somebody …
=> Feature/1426 implements CustomDataset
