fedbiomed/fedbiomed

- .github/actions/unit-tests/action.yml
- docs/tutorials/installation/0-basic-software-installation.md
- scripts/configure_conda
- scripts/fedbiomed_run
closes #787 
- Network component is managed through docker
- It is not required to be install unless user wants to run restful locally
This pull request does following changes: 
- makes network conda environment optionally installed
- removes network conda env activation before docker command in `fedbiomed_run`
- don't install network component before starting network in action.yml
- Adds note to installation guide to explain `fedbiomed-network` conda env is optional
- you offer the changes under …
> Make fedbiomed-network conda env optional

- .github/workflows/build-test.yml
- docs/user-guide/researcher/experiment.md
- fedbiomed/common/training_args.py
- fedbiomed/common/training_plans/_base_training_plan.py
- fedbiomed/common/training_plans/_sklearn_training_plan.py
- fedbiomed/common/training_plans/_torchnn.py
- tests/test_fedbiosklearn.py
- tests/test_torchnn.py
Closes #79 .
This PR introduces the option to set the random seed on the node at the beginning of the round.
There was a design choice to be made, related to the fact that Fed-BioMed does not store any state on the node between rounds. In fact, the constraint is even stricter: a Fed-BioMed node may even be restarted between two rounds!
The options I considered were:
Pros: it is clean. Even though it can lead to counterintuitive behaviour, once you are aware of this quirk it is very easy to understand what's happening and to compare different runs.
Cons: when using `exp.run()`, the same seed will be set at every round. This invalidates the users' expectations w.r.t. to randomization effects like shuffling the dataset, since it will always be shuffled in the same way
Pros: different rounds …
> Feature/79 Set random seed

- fedbiomed/researcher/experiment.py
- misc remove useless test for self._monitor
Fixes 833 (duplicate from 525)
**License**
```
```
The `CREDIT.md` …
> Fix 833/525 display incorrect round number after breakpoint load

- fedbiomed/common/constants.py
- fedbiomed/node/cli_utils/_database.py
- fedbiomed/node/dataset_manager.py
- tests/test_dataset_manager.py
This PR updates `cli.py` and `dataset_manager.remove_database` to use `dataset_id`  for deleting a dataset instead of  `tags`.
**License**
```
```
They shall retain the …
> Fixes dataset delete from CLI

- notebooks/declearn-with-pytorch.ipynb
Related to issue #909 
Changed the learning rate to the same we have in `101-getting-started` notebook
**License**
```
```
They shall retain the original license and …
> changing declearn optimizer learning rate

- .gitignore
Misc fix (regression): data dir is not saved
**License**
```
```
The `CREDIT.md` file and `credit/` directory …
> misc fix: regression, data dir is not saved

- fedbiomed/common/training_plans/_training_iterations.py
> Fix notebook failing when using `batch_maxnum`

- CHANGELOG.md
- RELEASE.md
- fedbiomed/common/constants.py
- scripts/fedbiomed_vpn
Fix #969 in v5.0.1
**License**
```
```
The `CREDIT.md` file and `credit/` directory shall be completed and …
> fix 969 fedbiomed_vpn time race issues

- fedbiomed/common/ipython.py
- fedbiomed/common/logger.py
- fedbiomed/common/utils/__init__.py
- fedbiomed/common/utils/_utils.py
- fedbiomed/researcher/experiment.py
- tests/test_ipython.py
- tests/test_utils.py
Fix #975 
Changes the display style of output ...
**License**
```
``` …
> fix message display in wrong cell

- docs/user-guide/researcher/training-plan.md
- fedbiomed/common/training_plans/_base_training_plan.py
- tests/test_fedbiosklearn.py
- tests/test_torchnn.py
Related to issue #952 : the newly implemented methods `export_model` and `import_model` of the training plan cannot be used directly through the `Tranining Plan`, and only once the Training plan has been loaded in the `Experiment`. 
This proposed fix adds:
1.  error messages when one call either `export_model` or `import_model` from the `TrainingPlan`
2. updates for documentation
- you did …
> Adding error message when using `import_model` and `export_model`  while model hasnot been instantiated

- fedbiomed/common/constants.py
- fedbiomed/transport/client.py
- fedbiomed/transport/node_agent.py
- fedbiomed/transport/server.py
- tests/test_transport_client.py
- tests/test_transport_node_agent.py
- tests/test_transport_server.py
Fix #980 #981
Review is mostly doing stability checks with some heavy tests (rather than code review)
**License**
```
```
They shall retain the original license and copyright …
> fix gRPC communication instabilities

- fedbiomed/researcher/job.py
Proposes a fix for the bug described in #992 
`TrainingReplies` are saved in breakpoints, keeping copies of what is sent back by Nodes. However, they may contain auxiliary_variables parameters received from `Nodes` that are non JSON serializable.
This fix proposes to save these auxiliary variables and non JSON serializable parameters into files, so we keep consistency with the notion of `TrainingReplies`.
-  There is one file for node auxiliary variable parameters at each `Round`: we may to optimize the way they are saved in order to reduce the number of files we have
- the auxiliary variable parameters are converted into a file during the auxiliary variable data extraction process. This might not be suitable with the purpose of the method (which is bsically to extract …
> Fix for declearn optimizer not able save breakpoint

- fedbiomed/researcher/federated_workflows/_experiment.py
- tests/test_experiment.py
- Tested by running breakpoint save and resume notebook
**License**
```
``` …
> Makes `save_aggregated_params` a public method

- fedbiomed/common/models/_model.py
- fedbiomed/common/models/_sklearn.py
- fedbiomed/common/models/_torch.py
- fedbiomed/common/training_plans/_base_training_plan.py
- fedbiomed/common/training_plans/_torchnn.py
- fedbiomed/researcher/federated_workflows/_experiment.py
- fedbiomed/researcher/federated_workflows/_training_plan_workflow.py
- tests/test_training_plan_workflow.py
- tests/testsupport/fake_training_plan.py
#1003 
This PR introduces persistent buffers parameters in breakpoints during secure aggregation. 
It also fixes some issues with model weight API, (#1010 ) by adding the only_trainable and exclude_buffers boolean in flatten and unflatten functions.
**License**
``` …
```
> Added buffers in breakpoints for secagg

- fedbiomed/node/node.py
- fedbiomed/node/round.py
- tests/test_round.py
Fix cleaning of node side temporary dirs (no issue associated).
How to test:
- launch 1 or 2 nodes, add MNIST dataset
- count files and list last files in `$FEDBIOMED_DIR/var`
```
ls -lart ./var | wc -l
ls -lart ./var | tail -20
```
- run `101-getting-started.ipynb` notebook
- count again files and list last files in `$FEDBIOMED_DIR/var`
- check that there are no more files in the directory (at least no temporary dir)
- …
> Fix cleaning of node side temporary dirs

- fedbiomed/common/training_plans/_base_training_plan.py
- fedbiomed/researcher/aggregators/aggregator.py
- fedbiomed/researcher/federated_workflows/_experiment.py
- fedbiomed/researcher/federated_workflows/_training_plan_workflow.py
- tests/test_training_plan_workflow.py
Closes #1049
**License**
```
``` …
> Provide a method to access Model class from training plan

- fedbiomed/common/training_plans/_torchnn.py
- fedbiomed/researcher/federated_workflows/_training_plan_workflow.py
Closes #1048
**License**
```
``` …
> adds option to switch on and off init_optimizer execution

- fedbiomed/researcher/federated_workflows/_experiment.py
- fedbiomed/researcher/federated_workflows/_federated_workflow.py
- fedbiomed/researcher/federated_workflows/_training_plan_workflow.py
- fedbiomed/researcher/federated_workflows/jobs/_job.py
- fedbiomed/researcher/federated_workflows/jobs/_training_job.py
- fedbiomed/researcher/federated_workflows/jobs/_training_plan_approval_job.py
> reorganize constructor arguments of federated workflow and job classes

- docs/user-guide/researcher/experiment.md
This PR refers to issue #1042 :
- add a section in the User Guide / Researcher / Experiment to describe the new argument share_persistent_buffers in the training arguments
**License**
```
```
Code files can be reused from another project with a compatible …
> Add section in user guide for buffers

- fedbiomed/common/tasks_queue.py
Tune filesystem persistent queue `chunk_size`.
Rationale:
- `chunk_size` defines the number of queue items stored per file, default is 100
- this space is used even when queue element won't be re-used (`task_done()` was run)
- the default value is probably oriented for small items, optimized for performance
- in our case, we use few queue items potentially very big (include model weights)
- for example in a test with 100 rounds, 10 nodes, model params ~50 MB it results in 50GB disk used for queues
Note: no associated issue.
This …
> tune queue size

- envs/vpn/docker/gui/build_files/Dockerfile
- scripts/fedbiomed_run
Fix #1091 with minimal change.
**License**
```
``` …
> Fix docker `gui` container build with new CLI syntax

- fedbiomed/common/secagg/_jls.py
- fedbiomed/common/secagg/_secagg_crypter.py
- tests/test_joye_libert.py
- tests/test_secagg_crypter.py
- address issue #1056 in `divide()` by using `uint64` to avoid overflow when summing several `uint32`. Problem was introduced by weighted average.
- misc robustify for
* `divide()` by raising an error if data would be lost by converting from `int` to `uint64` (which should not happen with < 2**32 nodes with current weighting function, but will avoid similar bug in the future)
* `quantize()` by making all type conversions of weight explicit, so it is clear the maximum supported `target_range` is 2**64
* `reverse_quantize()` by also making explicit the weight type conversions, plus raising an error if encoded weights values are outside of bounds, which would result in information loss (or means we have faulty input)
By opening …
> Fix secagg failures with 4+ nodes

- fedbiomed/common/constants.py
- fedbiomed/transport/client.py
- fedbiomed/transport/server.py
- tests/test_transport_client.py
- try mitigate #1100 by introducing gRPC client retries at application level
- #1097 add more gRPC client message when an error occurs
- fix message send retries on gRPC server
- refactor gRPC client `Listener` classes to factor code and clarify/simplify when possible
Run manual tests for these modifications before merging** (keep `batch_maxnum=100`)
```
self.fc1 = nn.Linear(9216, 12800)
self.fc2 = nn.Linear(12800, 10)
```
- you offer the changes under the same license agreement as the project, …
> Improve gRPC layer for stability

- .github/workflows/endurance-tests.yml
- tests/end2end/conftest.py
- tests/end2end/e2e_sklearn.py
- tests/end2end/endurance_e2e_big_neural_network.py
- tests/end2end/endurance_e2e_increased_number_of_nodes.py
- tests/end2end/experiments/training_plans/mnist_pytorch_training_plan.py
- tests/end2end/helpers/__init__.py
- tests/end2end/helpers/_datasets.py
> adds endurance test

- fedbiomed/node/secagg.py
- tests/end2end/helpers/_execution.py
- tests/end2end/helpers/_helpers.py
- tests/test_secagg_node.py
Complete #1152
**License**
```
``` …
> Fix e2e tests failure for secagg tests

- fedbiomed/common/exceptions.py
- fedbiomed/common/synchro.py
- fedbiomed/node/requests/_overlay.py
- tests/test_common_synchro.py
- tests/test_insert_untested_python_files_here.py
- tests/test_node.py
- tests/test_node_n2n_controller.py
- tests/test_node_n2n_router.py
- tests/test_node_overlay.py
Partial implementation of #942: add unit tests for some LOM secagg code
* `common/synchro.py`
* `node/requests/_n2n_router.py`
* `node/requests/_n2n_controller.py`
* `node/requests/_overlay.py`
**License**
```
```
Code files can be reused from another project with …
> Add unit tests for some LOM secagg new modules

- fedbiomed/researcher/secagg/_secure_aggregation.py
- tests/end2end/e2e_secure_aggregation.py
> Fix breakpoint dysfunction for secure aggregation (regression)

- tests/end2end/helpers/_execution.py
- tests/end2end/helpers/_helpers.py
Fix endurance test replacing os.fork with process spawn
**License**
```
``` …
> Fix endurance test replacing os.fork with process spawn

- fedbiomed/common/secagg/_lom.py
- fedbiomed/common/utils/_secagg_utils.py
- fedbiomed/researcher/secagg/_secure_aggregation.py
- tests/end2end/e2e_secure_aggregation.py
- tests/test_secure_aggregation.py
Address #1210 LOM secagg failing with "many nodes" scenarios:
- clarify cases where it should fail/succeed
- node side: give clearer message to user when failing due to limitations
- researcher side: fix a bug when aggregated value is >= 2**31 (and is converted to < 0 `int`)
Reviewer may want to (re) test scenarios of LOM secagg:
- success with 7 or 8 nodes
- failure with 9 or 10 nodes
- success with 10 nodes and `test_ratio: 0.4`
- you offer the changes under the same license agreement as the …
> Fix LOM secagg failure with some "many nodes" scenarios

- docs/getting-started/installation.md
- docs/user-guide/nodes/deploying-datasets.md
- fedbiomed/cli.py
- fedbiomed/common/cli.py
- fedbiomed/common/config.py
- tests/test_common_cli.py
- tests/test_root_cli.py
- removes dependencies to `fedbiomed.node` and `fedbiomed.researcher` existing in `fedbiomed.common.cli` (last remaining task in #1233 ?). New version written for v6 (replaces PR #1257 which was written for v5.4)
- add more unit tests to the `fedbiomed configuration` parser code + fixes several bugs found in this subparser
**License**
Project code …
> remove dependencies to fedbiomed.node in fedbiomed.common, for v6.

- envs/vpn/README.md
- envs/vpn/docker/node/build_files/entrypoint.bash
in containers
Misc fixes for VPN+containers mode:
- regression: no default training plan should now be allowed in container mode
- VPN documentation typos
No associated issue.
**License**
```
```
Code files can be reused from another project with a compatible …
> misc fixes for VPN+containers mode

- fedbiomed_gui/ui/src/App.js
- fedbiomed_gui/ui/src/pages/datasets/AddDataset.js
This PR solves the issue of active tab color tab in Add Dataset page. `Common Standards` tab had always active color background even `Medical Folder Dataset` tab selected.
**License**
```
```
Code files can be reused from another project with a compatible …
> Solves active tab color glitch in add dataset page

- fedbiomed/researcher/federated_workflows/_experiment.py
- tests/test_experiment.py
This closes #1127. 
**License**
```
```
The `CREDIT.md` file and `credit/` directory shall be completed and …
> Exception for empty list of nodes before starting a training job.

- fedbiomed/researcher/federated_workflows/_federated_workflow.py
Avoid the creation of a new empty and unused experiment folder when load_breakpoint is used. See detailed discussion in #1181 
Closes #1181 
**License**
```
```
They shall …
> Prevent creation a unused new experiment folder when load breakpoint

- docs/user-guide/researcher/configuration.md
- fedbiomed/common/config.py
- fedbiomed/common/constants.py
- fedbiomed/node/config.py
- fedbiomed/researcher/config.py
- fedbiomed/researcher/requests/_requests.py
- fedbiomed/transport/node_agent.py
- fedbiomed/transport/server.py
- tests/test_transport_node_agent.py
- tests/test_transport_server.py
- Introduces new config value for server to avoid node disconnections due to communication delay and big ML models
- Updates unittests
- Implements migration hook to provide backward compatibility for new config value
This PR party resolves some of the issue mentioned in  the issue #1251 
**License**
Project code files should begin with these …
> Introduces new configuration for `node_disconnection_timeout`

- fedbiomed_gui/server/routes/repository.py
- fedbiomed_gui/server/utils.py
- fedbiomed_gui/ui/src/pages/datasets/CommonStandards.js
- fedbiomed_gui/ui/src/pages/repository/index.js
It was caused by the function call `file_stats `in `repository.py` which caused the traversal of all subfiles when calculating file size.
Details can be seen in [Issue #1444](https://github.com/fedbiomed/fedbiomed/issues/1444)
> Fix issue that caused the GUI server to crash when adding a new dataset
